name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -e .
      - run: pip install ruff black mypy pytest
      - run: ruff check .
      - run: black --check .
      - run: mypy src || true
      - run: pytest
